services:
  reverseproxy:
    build: ./reverse
    container_name: reverseproxy
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - mi-red
    restart: always

  nginx:
    build: ./site1
    container_name: nginx
    depends_on:
      - reverseproxy
    networks:
      - mi-red
    restart: always

  apache:
    build: ./site2
    container_name: apache
    depends_on:
      - reverseproxy
    networks:
      - mi-red
    restart: always

networks:
  mi-red:
    driver: bridge